### ISSUE TITLE
not work on my ze620kl error

### ISSUE THREAD

**Issue by nando1413** [bluehomewu/ZenFone5_2018_ZE620KL_Unofficial_Unlock#7]
i using UL-ASUS_X00QD-ASUS-AOSP-17.0615.2003.20-1.1.1-user 

i follow original https://medium.com/@shakalaca/zenfone-ze620kl-zenfone-5-2018-unoffical-unlock-lock-method-e93f29b10a29 but errot too

FAILED (remote: 'Secret key is invalid, please update the secret key')

**Comment by bluehomewu** [comment]
Unofficial tool only works on 1st Android 10 beta version,and also you can't upgrade to newest version before.
If you upgrade to newest version,ASUS already fix this method, downgrade is not working at all.
